#!/bin/sh
alive=1
clear
echo -e ">>> Script for copying COMODO LOG file <<<\nFiles will be stored in the root direcotry of flash drive."
while [ $alive -eq 1 ]
do
	echo -e "\nMENU\n 1) Copy log files to flash drive \n 2) View log file destination folder \n 3) Exit \n 4) Reboot"
	echo -n "Your option: "
	read Option
	case $Option in
		1 ) echo -e "\n i - You may be asked for overwriting old file (y/n)" 
			cp -i /mnt/C/cce_linux/log/* /mnt/sdb1/
			echo -e "\nCopying has been successfully done if no errors appeared or if user didn't abandoned operation."
			;;
		2 ) echo -e "Destination folder should be /mnt/C/cce_linux/log ... trying to open" 
			pcmanfm /mnt/C/cce_linux/log
			;;
		3 ) echo "The end!"
			alive=0
	        	;;
		4 ) echo "Computer will be rebooted!"
			reboot
			echo -e "If computer will not reboot immediately, please reboot manually."
	        	;;
		* ) echo "Wrong option!"
			;;
	esac
done
